// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: charges.sql

package database

import (
	"context"
)

const addCharge = `-- name: AddCharge :exec
INSERT INTO charges (
    user_email, payment_intent_id, amount, status
)
VALUES (?, ?, ?, ?)
`

type AddChargeParams struct {
	UserEmail       string
	PaymentIntentID string
	Amount          int32
	Status          string
}

func (q *Queries) AddCharge(ctx context.Context, arg AddChargeParams) error {
	_, err := q.db.ExecContext(ctx, addCharge,
		arg.UserEmail,
		arg.PaymentIntentID,
		arg.Amount,
		arg.Status,
	)
	return err
}

const getChargesByUserEmail = `-- name: GetChargesByUserEmail :many
SELECT
    payment_intent_id,
    amount,
    user_email
FROM charges
WHERE
    status = "succeeded"
    AND user_email = ?
ORDER BY created_at DESC
`

type GetChargesByUserEmailRow struct {
	PaymentIntentID string
	Amount          int32
	UserEmail       string
}

func (q *Queries) GetChargesByUserEmail(ctx context.Context, userEmail string) ([]GetChargesByUserEmailRow, error) {
	rows, err := q.db.QueryContext(ctx, getChargesByUserEmail, userEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChargesByUserEmailRow
	for rows.Next() {
		var i GetChargesByUserEmailRow
		if err := rows.Scan(&i.PaymentIntentID, &i.Amount, &i.UserEmail); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
