// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (email, hwid) VALUES (?, ?)
`

type CreateUserParams struct {
	Email string
	Hwid  sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.Email, arg.Hwid)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    email,
    hwid,
    created_at,
    updated_at
FROM users
WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Hwid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByHWID = `-- name: GetUserByHWID :one
SELECT
    id,
    email,
    hwid,
    created_at,
    updated_at
FROM users
WHERE hwid = ?
`

func (q *Queries) GetUserByHWID(ctx context.Context, hwid sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByHWID, hwid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Hwid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetUserHWID = `-- name: ResetUserHWID :exec
UPDATE users
SET hwid = NULL
WHERE email = ?
`

func (q *Queries) ResetUserHWID(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, resetUserHWID, email)
	return err
}

const updateUserHWID = `-- name: UpdateUserHWID :exec
UPDATE users
SET hwid = ?
WHERE email = ?
`

type UpdateUserHWIDParams struct {
	Hwid  sql.NullString
	Email string
}

func (q *Queries) UpdateUserHWID(ctx context.Context, arg UpdateUserHWIDParams) error {
	_, err := q.db.ExecContext(ctx, updateUserHWID, arg.Hwid, arg.Email)
	return err
}
