FROM golang:tip-alpine3.22 AS builder

WORKDIR /app

RUN apk update && apk add --no-cache build-base

COPY go.mod go.sum ./
RUN go mod download

COPY . ./
RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o pw-equip main.go

# Final image
FROM alpine:3.22.0
WORKDIR /app
COPY --from=builder /app/pw-equip .

COPY ../static ./static
COPY ../templates ./templates
COPY ../css ./css
COPY ../.env-prod ./
COPY ../download ./download

RUN apk update && apk add mysql-client curl

HEALTHCHECK --interval=30s --timeout=30s --retries=3 CMD curl -f http://localhost/equip/health

EXPOSE 8080

CMD ["./pw-equip"]