FROM golang:tip-alpine3.22 AS builder

WORKDIR /app

RUN apk update && apk add --no-cache build-base

COPY go.mod go.sum ./
RUN go mod download

COPY . ./
RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o pw-equip ./cmd/server

# Final image
FROM alpine:3.22.0
WORKDIR /app

# Copy only the binary
COPY --from=builder /app/pw-equip .

# Install runtime dependencies
RUN apk update && apk add --no-cache mysql-client curl

HEALTHCHECK --interval=30s --timeout=30s --retries=3 CMD sh -c "curl -f http://127.0.0.1:$${API_PORT:-8989}/equip/health || exit 1"

EXPOSE 8989

CMD ["./pw-equip"]