// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Charge struct {
	ID              int32
	PaymentIntentID string
	Status          string
	Amount          int32
	UserEmail       string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type User struct {
	ID        int32
	Email     string
	Hwid      sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}
