name: Build Windows

on:
    push:
        branches: [main]
      
jobs:
  build:
    name: Build
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.5"
       
      - name: Set up Fyne
        run: go install fyne.io/tools/cmd/fyne@latest

      - name: Get Release Version
        id: get_version
        run: echo "VERSION=$(Get-Content version.txt)" >> $env:GITHUB_ENV

      - name: Build Windows
        run: cd cmd/client && fyne package -os windows --name pw-equip-changer.exe -icon media/icon.jpg -release --app-id ${{ env.VERSION }}

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pw-equip-changer-v${{ env.VERSION }}
          path: pw-equip-changer.exe
          overwrite: true

  release:
    needs: build
    runs-on: windows-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Get Release Version
        id: get_version
        run: echo "VERSION=$(Get-Content version.txt)" >> $env:GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/pw-equip-changer-v${{ env.VERSION }}/pw-equip-changer.exe
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
        
