name: Build Windows

on:
    push:
        branches: [main]
      
jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.5"
       
      - name: Set up Fyne
        run: go install fyne.io/tools/cmd/fyne@latest

      - name: Get Release Version
        id: get_version
        run: echo "VERSION=$(type version.txt)" >> $env:GITHUB_ENV

      - name: Build Windows
        run: fyne package -os windows --name pw-equip-changer.exe -icon media/icon.jpg -release --app-id ${{ env.VERSION }}
      
      - name: Upload Windows
        uses: actions/upload-artifact@v4
        with:
          path: pw-equip-changer.exe
          name: pw-equip-changer.exe
          overwrite: true
        
        
        
